fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib
    concat: git://github.com/ripienaar/puppet-concat.git
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
  symlinks:
    openvpn: "#{source_dir}"

